version: '3'

services:
  react_frontend:
    container_name: react_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USERPOLLING=true

